### PR TITLE
Support Symfony 5.4

### PR DESCRIPTION
**Pull request by fre5h**

### CODE REVIEW

**Comment by hhamon** [comment]
Symfony 5.4.0 is out :)

**Comment by fre5h** [comment]
@hhamon new bundle release is ready

**Comment by hhamon** [comment]
@fre5h Awesome, thank you!

**Comment by alex-bacart** [comment]
Symfony 6.0 is also released. @fre5h can you please tell when your bundle will support it? Maybe at least in dev-main brunch?

**Comment by fre5h** [comment]
@alex-bacart I will work on it. Hope it will be quickly

**Pull request merged**
