### PR TITLE
Simplify AbstractEnumType a bit

### PR DESCRIPTION
**Pull request by stloyd**
- don't use `in_array()` if `isset()` is possible,
- don't call internally methods that can be simplified to direct calls

### CODE REVIEW

**Comment by jroussel** [comment]
Hello,

I have just updated my vendors with composer and retrieved 4.1 tag but I have 2 errors :
- when I am trying to use an enum, I get Invalid value "..." for ENUM "..." in vendor/fresh/doctrine-enum-bundle/DBAL/Types/AbstractEnumType.php at line 49
- command "doctrine:schema:create" seems also generate wrong SQL for ENUM columns (empty values)

It works fine when I force "4.0" in my composer.json file (I am using PHP 5.4)

**Comment by fre5h** [comment]
@stloyd Can you take a look, it is after your update

**Comment by fre5h** [comment]
@jroussel Sorry, but I couldn't reproduce this bug. Are sure about it? Can you reproduce it again on your computer?

**Comment by fre5h** [comment]
Travis CI is also configured to run tests on PHP 5.4 https://github.com/fre5h/DoctrineEnumBundle/blob/master/.travis.yml#L5
All tests in this PR passed, if there are some issues according to the PHP versions tests must be failed

**Comment by jroussel** [comment]
Hi, thank you for getting back to me.
I will check it again tomorrow.

On Thursday, 21 January 2016, Artem Genvald <notifications@github.com>
wrote:

> Travis CI is also configured to run tests on PHP 5.4
> https://github.com/fre5h/DoctrineEnumBundle/blob/master/.travis.yml#L5
> All tests in this PR passed, if there are some issues according to the PHP
> versions tests must be failed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fre5h/DoctrineEnumBundle/pull/43#issuecomment-173653049>
> .
>


-- 
Envoyé de mon iPhone

**Comment by jroussel** [comment]
Hello,

I juste re-check this morning and still have this strange behavior :(

Here is my entity class

class UserCategoryOptin
{
    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="User", inversedBy="user_category_optins")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="user_category_optins")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @DoctrineAssert\Enum(entity="Marcom\AceBundle\Entity\Enum\UserCategoryOptinEnum")
     * @ORM\Column(type="UserCategoryOptinEnum", nullable=false)
     */
    private $optin;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $some;
}

And my Enum class

class UserCategoryOptinEnum extends AbstractEnum
{
    const NONE = 'none';
    const NO   = 'no';
    const YES  = 'yes';
    const SOME = 'some';

    public static function getChoices()
    {
        return array(
            self::NONE => 'None',
            self::NO   => 'No',
            self::YES  => 'Yes',
            self::SOME => 'Some',
        );
    }
}

With version 4.0, here is the result of "php app/console doctrine:schema:create"

CREATE TABLE user_category_optin (user_id INT NOT NULL, category_id INT NOT NULL, optin ENUM('none', 'no', 'yes', 'some') NOT NULL COMMENT '(DC2Type:UserCategoryOptinEnum)', some LONGTEXT DEFAULT NULL, INDEX IDX_78047B30A76ED395 (user_id), INDEX IDX_78047B3012469DE2 (category_id), PRIMARY KEY(user_id, category_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

And with 4.1 (nothing change in my code)

CREATE TABLE user_category_optin (user_id INT NOT NULL, category_id INT NOT NULL, optin ENUM() NOT NULL COMMENT '(DC2Type:UserCategoryOptinEnum)', some LONGTEXT DEFAULT NULL, INDEX IDX_78047B30A76ED395 (user_id), INDEX IDX_78047B3012469DE2 (category_id), PRIMARY KEY(user_id, category_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

**Comment by fre5h** [comment]
What exactly version of PHP do you have? 5.4.what?

**Comment by jroussel** [comment]
PHP Version 5.4.45-1~dotdeb+6.1

**Comment by fre5h** [comment]
Ok. I'll check it. You can use 4.0 version until

**Comment by stloyd** [comment]
There reason for this is that @jroussel used `getChoices()` method to declare enum options, not the internal array. So yes, this is BC break right now if someone implements this way the enum.

**Comment by fre5h** [comment]
@stloyd Thanks. I didn't notice.

So @jroussel only you need to change your class to and it will work

```php
class UserCategoryOptinEnum extends AbstractEnum
{
    const NONE = 'none';
    const NO = 'no';
    const YES = 'yes';
    const SOME = 'some';

    protected static $choices = [
        self::NONE => 'None',
        self::NO   => 'No',
        self::YES  => 'Yes',
        self::SOME => 'Some',
    ];
}
```

**Pull request merged**
