### PR TITLE
Fix Symfony 3 choices field type compatibility

### LINKED ISSUE #40: Enum form choices backwards when using Symfony 3
Prior to Symfony 3, there was the form choice option of "choices_as_values" which would use arrays as such:

```php
[
     'value'=>'label'
]
```
when using 'choices_as_values' => false which is how this the choices are handled for the enums. This means that in symfony 3, the enum value is shown as the label and the label is shown as the value.

Later they in symfony 3, they removed the 'choices_as_values' option from the choices form type and set the form type to be as if 'choices_as_values' is true. This means that in your enum choices array you need to make them as:

```php
[
     'label'=>'value'
]
```

Doing this displays the values and labels correctly, however upon submitting the form, you'll receive the error that "The value you selected is not a valid choice." This is because your choices array is now flipped from the way that the enums type checks for the valid value.

I was able to get around this by using array_flip() in my form builder ```array_flip(\Acme\Enum\MyEnum::getChoices())``` but I feel like this is something that should be addressed in the getChoices() method, or in the place that the submitted value is checked.

### PR DESCRIPTION
**Pull request by jaikdean**
This PR should fix #40, #47 and #48.

### CODE REVIEW

**Comment by fre5h** [comment]
Nice work! Thanks!

**Comment by fre5h** [comment]
@jaikdean What about a test for LegacyFormHelper?

**Comment by jaikdean** [comment]
@fre5h I'll get some written.

**Comment by fre5h** [comment]
Ok, then I am waiting for your test and final Travis CI check and merge it

**Comment by jaikdean** [comment]
Tests added.

**Comment by fre5h** [comment]
There are some failed coding standards in the test, but ignore them. Tests are not required always to follow standards and should be simple and readable. I will refactor it and reconfig Travis.
Thanks for pull request

**Pull request merged**
